
import React, { useEffect, useRef, useState, useCallback } from 'react';
import { createRoot } from 'react-dom/client';
import * as THREE from 'three';
// We rely on the importmap to resolve 'three/examples/jsm/...' to the CDN URL
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass';
import { FilesetResolver, HandLandmarker } from '@mediapipe/tasks-vision';

// --- Configuration & Constants ---
const isMobile = window.innerWidth < 1024; // Treat tablets as mobile-ish for performance
// Optimized counts for high FPS on mobile
const ORNAMENT_COUNT = isMobile ? 320 : 650; 
const STARDUST_COUNT = isMobile ? 800 : 2200;
const SNOW_COUNT = isMobile ? 180 : 500;

const TREE_HEIGHT = 28;
const TREE_BASE_RADIUS = 11;
const COLORS = {
  PINK: 0xFFB7C5,   // Sakura Pink
  GOLD: 0xFFE5B4,   // Peach Gold
  MINT: 0xA0E6B6    // Soft Mint
};

// --- AI Generated Default Images (Base64 Placeholders for "Gemini Generated" Art) ---
// Style: Romantic Watercolor / Crayon, Pastel Christmas
const DEFAULT_IMAGES = [
    // 1. Cute Reindeer & Snowman
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2ZmZjBmNSIvPjxjaXJjbGUgY3g9IjI1NiIgY3k9IjI1NiIgcj0iMTgwIiBmaWxsPSIjZmZkMWRjIiBvcGFjaXR5PSIwLjMiLz48dGV4dCB4PSI1MCUiIHk9IjUwJSIgZHM9IjAuNSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1zaXplPSI4MCI+8J+RgDwvdGV4dD48L3N2Zz4=",
    // 2. Romantic Christmas Tree
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2ZmZjBmNSIvPjxjaXJjbGUgY3g9IjI1NiIgY3k9IjI1NiIgcj0iMTgwIiBmaWxsPSIjZDRmMGZjIiBvcGFjaXR5PSIwLjMiLz48dGV4dCB4PSI1MCUiIHk9IjUwJSIgZHM9IjAuNSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1zaXplPSI4MCI+8J+OjDwvdGV4dD48L3N2Zz4=",
    // 3. Cozy Fireplace & Stockings
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIiB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiI+PHJlY3Qgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgZmlsbD0iI2ZmZjBmNSIvPjxjaXJjbGUgY3g9IjI1NiIgY3k9IjI1NiIgcj0iMTgwIiBmaWxsPSIjZmZlNGIxIiBvcGFjaXR5PSIwLjMiLz48dGV4dCB4PSI1MCUiIHk9IjUwJSIgZHM9IjAuNSIgZG9taW5hbnQtYmFzZWxpbmU9Im1pZGRsZSIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1zaXplPSI4MCI+8J+TgDwvdGV4dD48L3N2Zz4="
];

// Note: In a real production app, these would be high-res JPGs generated by Imagen 3/Gemini Pro Vision. 
// For this single-file demo, we use SVG placeholders to keep the file size manageable while providing visual interest.

// --- Texture Generators (Cached) ---

const createSoftGradientTexture = (colorA: string, colorB: string) => {
  const size = 128;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return new THREE.Texture();

  // Smoother gradient with easing and pearlescent hint
  const grad = ctx.createRadialGradient(size/2, size/2, 0, size/2, size/2, size/2);
  grad.addColorStop(0, '#ffffff'); // Center highlight
  grad.addColorStop(0.3, colorA);
  grad.addColorStop(0.8, colorB);
  grad.addColorStop(1, colorB);

  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, size, size);

  const texture = new THREE.CanvasTexture(canvas);
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
};

const createParticleTexture = () => {
  const size = 64;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return new THREE.Texture();

  const grad = ctx.createRadialGradient(size/2, size/2, 0, size/2, size/2, size/2);
  grad.addColorStop(0, 'rgba(255, 255, 255, 1)');
  grad.addColorStop(0.3, 'rgba(255, 255, 255, 0.6)');
  grad.addColorStop(0.6, 'rgba(255, 240, 245, 0.2)');
  grad.addColorStop(1, 'rgba(255, 255, 255, 0)');

  ctx.fillStyle = grad;
  ctx.fillRect(0, 0, size, size);

  const texture = new THREE.CanvasTexture(canvas);
  return texture;
};

const createStripeTexture = () => {
  const size = 256;
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return new THREE.Texture();

  ctx.fillStyle = '#FFF0F5'; // Lavender Blush
  ctx.fillRect(0, 0, size, size);

  ctx.fillStyle = '#FFB7C5'; // Pink
  const stripeCount = 4;
  const stripeWidth = size / stripeCount;
  
  ctx.translate(size/2, size/2);
  ctx.rotate(Math.PI / 4);
  ctx.translate(-size, -size);

  for(let i = 0; i < stripeCount * 3; i++) {
     ctx.fillRect(i * stripeWidth * 2, -size, stripeWidth, size * 4);
  }

  const texture = new THREE.CanvasTexture(canvas);
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  texture.colorSpace = THREE.SRGBColorSpace;
  return texture;
};

// --- Helper Functions ---
const getTreePosition = (index: number, total: number) => {
  const normalizedIndex = index / total;
  const y = (1 - normalizedIndex) * TREE_HEIGHT - (TREE_HEIGHT / 2); 
  const radius = Math.pow(normalizedIndex, 0.8) * TREE_BASE_RADIUS;
  const angle = index * 2.39996;
  const x = Math.cos(angle) * radius;
  const z = Math.sin(angle) * radius;
  return new THREE.Vector3(x, y, z);
};

const getOrbitParams = () => {
  const radius = 8 + Math.random() * 30; 
  const angle = Math.random() * Math.PI * 2;
  const speed = (0.1 + Math.random() * 0.3) * (Math.random() > 0.5 ? 1 : -1); 
  const y = (Math.random() - 0.5) * 25; 
  return { radius, angle, speed, y };
};

// --- Types ---
type InstanceData = {
  treePos: THREE.Vector3;
  orbitRadius: number;
  orbitStartAngle: number;
  orbitSpeed: number;
  orbitY: number;
  meshIndex: number;
  instanceId: number;
  currentPos: THREE.Vector3;
  currentRot: THREE.Euler;
  currentScale: number;
  rotationSpeed: THREE.Vector3;
  phase: number;
  // Physics Sim
  velocity: THREE.Vector3;
};

const App = () => {
  const mountRef = useRef<HTMLDivElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const cursorRef = useRef<HTMLDivElement>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);
  
  const [loading, setLoading] = useState(true);
  const [started, setStarted] = useState(false);
  const [gesture, setGesture] = useState<string>('✨ 等待唤醒...');
  // Initialize with DEFAULT_IMAGES to avoid empty scene
  const [userPhotos, setUserPhotos] = useState<string[]>(DEFAULT_IMAGES);
  const [isPlaying, setIsPlaying] = useState(false);
  
  const sceneRef = useRef<THREE.Scene | null>(null);
  const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const rendererRef = useRef<THREE.WebGLRenderer | null>(null);
  const composerRef = useRef<EffectComposer | null>(null);
  const handLandmarkerRef = useRef<HandLandmarker | null>(null);
  
  const instancedMeshesRef = useRef<THREE.InstancedMesh[]>([]);
  const particlesDataRef = useRef<InstanceData[]>([]);
  const photoMeshesRef = useRef<THREE.Mesh[]>([]);
  const starRef = useRef<THREE.Group | null>(null);
  const stardustRef = useRef<THREE.Points | null>(null);
  const snowRef = useRef<THREE.Points | null>(null);
  const frameIdRef = useRef<number>(0);

  const ambientLightRef = useRef<THREE.AmbientLight | null>(null);
  const mainLightRef = useRef<THREE.PointLight | null>(null);
  
  const stateRef = useRef<'TREE' | 'FLOAT' | 'FOCUS'>('TREE');
  const focusedPhotoIndex = useRef<number>(-1);
  
  // Interaction Refs
  const targetHandPosRef = useRef<{x: number, y: number}>({ x: 0, y: 0 });
  const visualHandPosRef = useRef<{x: number, y: number}>({ x: 0, y: 0 });
  const lastDetectionTimeRef = useRef<number>(0);
  
  // 3D Space Hand Position for Collision
  const handWorldPosRef = useRef<THREE.Vector3>(new THREE.Vector3(0, -1000, 0));

  const panRef = useRef<{x: number, y: number}>({ x: 0, y: 0 });
  const cameraOffsetRef = useRef<{x: number, y: number}>({ x: 0, y: 0 });
  const zoomRef = useRef<number>(1.0);
  const isDraggingRef = useRef<boolean>(false);
  const lastMousePosRef = useRef<{x: number, y: number}>({ x: 0, y: 0 });
  const lastTouchDistanceRef = useRef<number>(0);
  const gestureHistoryRef = useRef<string[]>([]);
  const lastGestureTimeRef = useRef<number>(0);

  // FPS Monitoring & Dynamic Quality
  const lastFrameTimeRef = useRef<number>(0);
  const qualityLevelRef = useRef<number>(3); // 3=Ultra, 2=High, 1=Med, 0=Low
  const lowFpsCountRef = useRef<number>(0);

  // Materials Refs for dynamic updates
  const matRefs = useRef<THREE.MeshPhysicalMaterial[]>([]);

  // Init MediaPipe
  useEffect(() => {
    const initVision = async () => {
      try {
        const vision = await FilesetResolver.forVisionTasks(
          "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.8/wasm"
        );
        handLandmarkerRef.current = await HandLandmarker.createFromOptions(vision, {
          baseOptions: {
            modelAssetPath: `https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task`,
            delegate: "GPU"
          },
          runningMode: "VIDEO",
          numHands: 1
        });
        setLoading(false);
      } catch (error: any) {
        console.error("Failed to load MediaPipe:", error);
      }
    };
    initVision();
  }, []);

  // Init Three.js
  useEffect(() => {
    if (!mountRef.current) return;

    const scene = new THREE.Scene();
    scene.fog = new THREE.FogExp2(0x2e1c2b, 0.012); 
    sceneRef.current = scene;

    const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
    camera.position.set(0, 0, 48);
    cameraRef.current = camera;

    const renderer = new THREE.WebGLRenderer({ 
        antialias: true, 
        alpha: true,
        powerPreference: 'high-performance' 
    });
    renderer.setSize(window.innerWidth, window.innerHeight);
    // Start at device capability, degrade if needed
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); 
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1.2;
    mountRef.current.appendChild(renderer.domElement);
    rendererRef.current = renderer;

    // Post Processing - Optimized Bloom
    const renderScene = new RenderPass(scene, camera);
    const bloomRes = new THREE.Vector2(window.innerWidth / (isMobile?2:1), window.innerHeight / (isMobile?2:1));
    const bloomPass = new UnrealBloomPass(bloomRes, 1.5, 0.4, 0.85);
    bloomPass.threshold = 0.72; 
    bloomPass.strength = isMobile ? 0.4 : 0.65;   
    bloomPass.radius = isMobile ? 0.6 : 1.1;     
    
    const composer = new EffectComposer(renderer);
    composer.addPass(renderScene);
    composer.addPass(bloomPass);
    composerRef.current = composer;

    // Lights
    const ambientLight = new THREE.AmbientLight(0xfff0f5, 0.7); 
    scene.add(ambientLight);
    ambientLightRef.current = ambientLight;

    const mainLight = new THREE.PointLight(0xffd1dc, 2.0, 120); 
    mainLight.position.set(10, 20, 20);
    scene.add(mainLight);
    mainLightRef.current = mainLight;
    
    const fillLight = new THREE.PointLight(0xe0ffff, 1.2, 100); 
    fillLight.position.set(-15, -10, 15);
    scene.add(fillLight);

    // Materials - Enhanced Pearlescent / Iridescent
    const pinkGradTexture = createSoftGradientTexture('#FFB7C5', '#FFF0F5');
    const goldGradTexture = createSoftGradientTexture('#FFE5B4', '#FFF8DC');
    const stripeTexture = createStripeTexture();

    const matPearl = new THREE.MeshPhysicalMaterial({ 
      color: 0xffffff, // White base
      metalness: 0.1, 
      roughness: 0.2, 
      clearcoat: 1.0,
      clearcoatRoughness: 0.1,
      sheen: 1.5, // Strong sheen
      sheenColor: 0xffc1cc, // Pink sheen
      iridescence: 1.0,     // Strong iridescent effect
      iridescenceIOR: 1.33, // Water-like/Pearl-like refraction
      iridescenceThicknessRange: [100, 400]
    });
    
    const matJellyPink = new THREE.MeshPhysicalMaterial({ 
      map: pinkGradTexture,
      color: 0xffffff,
      roughness: 0.15,
      metalness: 0.1,
      transmission: 0.92, // High glass-like transmission
      thickness: 1.5,
      clearcoat: 1.0,
      iridescence: 0.4,
      iridescenceIOR: 1.4
    });
    
    const matGold = new THREE.MeshPhysicalMaterial({ 
      map: goldGradTexture,
      color: 0xffd700,
      roughness: 0.35,
      metalness: 0.6,
      clearcoat: 0.8,
      sheen: 1.0,
      sheenColor: 0xffd700
    });
    
    const matMint = new THREE.MeshPhysicalMaterial({ 
      color: COLORS.MINT,
      roughness: 0.2,
      metalness: 0.1,
      transmission: 0.7,
      thickness: 1.2,
      clearcoat: 1.0,
      sheen: 0.8,
      sheenColor: 0xffffff
    });
    
    const matCandy = new THREE.MeshPhysicalMaterial({
        map: stripeTexture, 
        roughness: 0.3,
        metalness: 0.0,
        clearcoat: 0.9, 
        clearcoatRoughness: 0.1
    });

    matRefs.current = [matJellyPink, matGold, matPearl, matMint, matCandy];

    // Geometries
    const geoSphere = new THREE.SphereGeometry(0.6, 12, 12); // Lower poly for mobile
    const geoBox = new THREE.BoxGeometry(0.85, 0.85, 0.85); 
    const geoTorus = new THREE.TorusGeometry(0.4, 0.22, 12, 18); 

    const meshDefinitions = [
        { id: 'jelly_pink', geo: geoSphere, mat: matJellyPink },
        { id: 'gold_satin', geo: geoSphere, mat: matGold },
        { id: 'pearl', geo: geoSphere, mat: matPearl },
        { id: 'mint_ring', geo: geoTorus, mat: matMint },
        { id: 'candy_box', geo: geoBox, mat: matCandy },
    ];

    const distribution = [0.3, 0.25, 0.2, 0.15, 0.1]; 
    const counts = distribution.map(d => Math.floor(ORNAMENT_COUNT * d));
    
    const instancedMeshes: THREE.InstancedMesh[] = [];
    const particlesData: InstanceData[] = [];
    
    meshDefinitions.forEach((def, index) => {
        const count = counts[index];
        const mesh = new THREE.InstancedMesh(def.geo, def.mat, count);
        mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);
        scene.add(mesh);
        instancedMeshes.push(mesh);

        const dummy = new THREE.Object3D();
        for(let i=0; i<count; i++) {
            const totalIndex = particlesData.length;
            const treePos = getTreePosition(totalIndex, ORNAMENT_COUNT);
            const orbitParams = getOrbitParams();
            
            dummy.position.copy(treePos);
            dummy.rotation.set(Math.random()*Math.PI, Math.random()*Math.PI, 0);
            const scale = 0.5 + Math.random() * 0.7;
            dummy.scale.setScalar(scale);
            dummy.updateMatrix();
            
            mesh.setMatrixAt(i, dummy.matrix);

            particlesData.push({
                treePos,
                orbitRadius: orbitParams.radius,
                orbitStartAngle: orbitParams.angle,
                orbitSpeed: orbitParams.speed,
                orbitY: orbitParams.y,
                meshIndex: index,
                instanceId: i,
                currentPos: treePos.clone(),
                currentRot: new THREE.Euler(dummy.rotation.x, dummy.rotation.y, dummy.rotation.z),
                currentScale: scale,
                rotationSpeed: new THREE.Vector3(
                    (Math.random()-0.5)*0.02, (Math.random()-0.5)*0.02, (Math.random()-0.5)*0.02
                ),
                phase: Math.random() * Math.PI * 2,
                velocity: new THREE.Vector3(0,0,0) // Init velocity
            });
        }
    });

    instancedMeshesRef.current = instancedMeshes;
    particlesDataRef.current = particlesData;

    // Stardust with Flowing Animation capability
    const stardustGeo = new THREE.BufferGeometry();
    const stardustPos = new Float32Array(STARDUST_COUNT * 3);
    const stardustRandoms = new Float32Array(STARDUST_COUNT);

    for(let i=0; i<STARDUST_COUNT; i++) {
        const r = 15 + Math.random() * 45;
        const theta = Math.random() * Math.PI * 2;
        const phi = Math.acos(2 * Math.random() - 1);
        stardustPos[i*3] = r * Math.sin(phi) * Math.cos(theta);
        stardustPos[i*3+1] = (Math.random() - 0.5) * 60; 
        stardustPos[i*3+2] = r * Math.sin(phi) * Math.sin(theta);
        stardustRandoms[i] = Math.random();
    }
    stardustGeo.setAttribute('position', new THREE.BufferAttribute(stardustPos, 3));
    stardustGeo.setAttribute('aRandom', new THREE.BufferAttribute(stardustRandoms, 1));
    
    const stardustMat = new THREE.PointsMaterial({
        color: 0xFFF0F5,
        size: 0.6, 
        map: createParticleTexture(),
        transparent: true,
        opacity: 0.6,
        depthWrite: false,
        blending: THREE.AdditiveBlending,
    });
    const stardust = new THREE.Points(stardustGeo, stardustMat);
    scene.add(stardust);
    stardustRef.current = stardust;

    // Snow
    const snowGeo = new THREE.BufferGeometry();
    const snowPos = new Float32Array(SNOW_COUNT * 3);
    for(let i=0; i<SNOW_COUNT; i++) {
        snowPos[i*3] = (Math.random() - 0.5) * 80;   
        snowPos[i*3+1] = (Math.random() - 0.5) * 60; 
        snowPos[i*3+2] = (Math.random() - 0.5) * 80; 
    }
    snowGeo.setAttribute('position', new THREE.BufferAttribute(snowPos, 3));
    const snowMat = new THREE.PointsMaterial({
        color: 0xffffff,
        size: 0.7,
        map: createParticleTexture(),
        transparent: true,
        opacity: 0.8,
        depthWrite: false
    });
    const snowMesh = new THREE.Points(snowGeo, snowMat);
    scene.add(snowMesh);
    snowRef.current = snowMesh;

    // Star
    const starGroup = new THREE.Group();
    const starGeo = new THREE.OctahedronGeometry(1.5, 0); 
    const starMat = new THREE.MeshBasicMaterial({ color: 0xfffeb8, transparent: true, opacity: 0.9 });
    const starMesh = new THREE.Mesh(starGeo, starMat);
    const haloGeo = new THREE.SphereGeometry(2.5, 16, 16);
    const haloMat = new THREE.MeshBasicMaterial({ color: 0xffd700, transparent: true, opacity: 0.2 });
    const haloMesh = new THREE.Mesh(haloGeo, haloMat);
    starGroup.add(starMesh);
    starGroup.add(haloMesh);
    starGroup.position.set(0, TREE_HEIGHT/2 + 2, 0);
    scene.add(starGroup);
    starRef.current = starGroup;

    const handleResize = () => {
      if (!cameraRef.current || !rendererRef.current || !composerRef.current) return;
      cameraRef.current.aspect = window.innerWidth / window.innerHeight;
      cameraRef.current.updateProjectionMatrix();
      rendererRef.current.setSize(window.innerWidth, window.innerHeight);
      composerRef.current.setSize(window.innerWidth, window.innerHeight);
    };
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
      if (mountRef.current && renderer.domElement) {
        mountRef.current.removeChild(renderer.domElement);
      }
      matRefs.current.forEach(m => m.dispose());
      [geoSphere, geoBox, geoTorus].forEach(g => g.dispose());
    };
  }, []);

  // Update Photos in Scene
  useEffect(() => {
    if (!sceneRef.current) return;
    
    // Clear old photos
    photoMeshesRef.current.forEach(m => sceneRef.current?.remove(m));
    photoMeshesRef.current = [];
    
    // Create new photos
    const photoGeo = new THREE.PlaneGeometry(5, 5); 
    userPhotos.forEach((url, i) => {
        const loader = new THREE.TextureLoader();
        loader.load(url, (tex) => {
            tex.colorSpace = THREE.SRGBColorSpace;
            const mat = new THREE.MeshBasicMaterial({ 
                map: tex, 
                side: THREE.DoubleSide,
                transparent: true,
                opacity: 0.95
            });
            const mesh = new THREE.Mesh(photoGeo, mat);
            
            // Assign orbit params
            const orbit = getOrbitParams();
            // Assign fixed tree pos
            const treePos = getTreePosition(i * 15 + 10, ORNAMENT_COUNT); 
            // Make photos float slightly outside tree
            treePos.multiplyScalar(1.2); 

            mesh.userData = {
                orbitRadius: orbit.radius,
                orbitAngle: orbit.angle,
                orbitSpeed: orbit.speed * 0.5,
                orbitY: orbit.y,
                treePos: treePos
            };
            
            sceneRef.current?.add(mesh);
            photoMeshesRef.current.push(mesh);
        });
    });
  }, [userPhotos]);
  
  // Interaction Logic
  useEffect(() => {
    const handleMove = (x: number, y: number) => {
        if (!isDraggingRef.current) {
            // Unproject mouse/touch to world space for collision
            if (cameraRef.current) {
                const vec = new THREE.Vector3();
                const pos = new THREE.Vector3();
                vec.set((x / window.innerWidth) * 2 - 1, -(y / window.innerHeight) * 2 + 1, 0.5);
                vec.unproject(cameraRef.current);
                vec.sub(cameraRef.current.position).normalize();
                const distance = -cameraRef.current.position.z / vec.z;
                pos.copy(cameraRef.current.position).add(vec.multiplyScalar(distance));
                // Clamp slightly to scene bounds
                handWorldPosRef.current.copy(pos);
            }
            return;
        }

        lastDetectionTimeRef.current = Date.now();
        const deltaX = x - lastMousePosRef.current.x;
        const deltaY = y - lastMousePosRef.current.y;
        lastMousePosRef.current = { x, y };

        if (stateRef.current === 'FOCUS') {
            const sensitivity = 0.03 / zoomRef.current;
            panRef.current.x += deltaX * sensitivity;
            panRef.current.y -= deltaY * sensitivity;
        } else if (stateRef.current === 'FLOAT') {
            const sensitivity = 0.003;
            cameraOffsetRef.current.x -= deltaX * sensitivity;
            cameraOffsetRef.current.y += deltaY * sensitivity;
        }
    };
    const handleTouchStart = (e: TouchEvent) => {
       if (stateRef.current !== 'FOCUS' && stateRef.current !== 'FLOAT') return;
       if (e.touches.length === 1) {
           isDraggingRef.current = true;
           lastMousePosRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
       } else if (e.touches.length === 2) {
           const dx = e.touches[0].clientX - e.touches[1].clientX;
           const dy = e.touches[0].clientY - e.touches[1].clientY;
           lastTouchDistanceRef.current = Math.sqrt(dx*dx + dy*dy);
           isDraggingRef.current = false;
       }
       lastDetectionTimeRef.current = Date.now();
    };
    const handleTouchMove = (e: TouchEvent) => {
        if (e.cancelable) e.preventDefault(); 
        if (e.touches.length === 1) handleMove(e.touches[0].clientX, e.touches[0].clientY);
        else if (e.touches.length === 2) {
            const dx = e.touches[0].clientX - e.touches[1].clientX;
            const dy = e.touches[0].clientY - e.touches[1].clientY;
            const dist = Math.sqrt(dx*dx + dy*dy);
            if (lastTouchDistanceRef.current > 0) {
                const delta = dist - lastTouchDistanceRef.current;
                zoomRef.current += delta * 0.005;
                zoomRef.current = Math.max(0.5, Math.min(zoomRef.current, 3.0));
            }
            lastTouchDistanceRef.current = dist;
            lastDetectionTimeRef.current = Date.now();
        }
    };
    const handleTouchEnd = () => { 
        isDraggingRef.current = false; 
        lastTouchDistanceRef.current = 0; 
        // Reset hand world pos to prevent collision when not touching
        handWorldPosRef.current.set(0, -1000, 0);
    };
    const handleMouseDown = (e: MouseEvent) => {
       if (stateRef.current !== 'FOCUS' && stateRef.current !== 'FLOAT') return;
       isDraggingRef.current = true;
       lastMousePosRef.current = { x: e.clientX, y: e.clientY };
       lastDetectionTimeRef.current = Date.now();
    };
    const handleMouseMove = (e: MouseEvent) => handleMove(e.clientX, e.clientY);
    const handleMouseUp = () => { isDraggingRef.current = false; };
    const handleWheel = (e: WheelEvent) => {
        if (stateRef.current !== 'FOCUS' && stateRef.current !== 'FLOAT') return;
        zoomRef.current += e.deltaY * -0.001;
        zoomRef.current = Math.max(0.5, Math.min(zoomRef.current, 3.0));
        lastDetectionTimeRef.current = Date.now();
    };

    window.addEventListener('mousedown', handleMouseDown);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    window.addEventListener('wheel', handleWheel);
    window.addEventListener('touchstart', handleTouchStart, { passive: false });
    window.addEventListener('touchmove', handleTouchMove, { passive: false });
    window.addEventListener('touchend', handleTouchEnd);
    return () => {
        window.removeEventListener('mousedown', handleMouseDown);
        window.removeEventListener('mousemove', handleMouseMove);
        window.removeEventListener('mouseup', handleMouseUp);
        window.removeEventListener('wheel', handleWheel);
        window.removeEventListener('touchstart', handleTouchStart);
        window.removeEventListener('touchmove', handleTouchMove);
        window.removeEventListener('touchend', handleTouchEnd);
    };
  }, []);

  // Main Loop
  const animate = useCallback(() => {
    if (!started || !cameraRef.current || !sceneRef.current) return;

    const now = performance.now();
    const time = now * 0.001;
    const delta = now - lastFrameTimeRef.current;
    lastFrameTimeRef.current = now;

    // Dynamic Quality Scaling
    if (delta > 20) {
        lowFpsCountRef.current++;
        if (lowFpsCountRef.current > 60 && qualityLevelRef.current > 0) { 
             lowFpsCountRef.current = 0;
             qualityLevelRef.current--;
             if (rendererRef.current && composerRef.current) {
                 if (qualityLevelRef.current === 2) rendererRef.current.setPixelRatio(1); 
                 else if (qualityLevelRef.current === 1) composerRef.current.passes = [composerRef.current.passes[0]]; 
             }
        }
    } else {
        lowFpsCountRef.current = Math.max(0, lowFpsCountRef.current - 1);
    }

    // Dynamic Material Updates (Breathing Iridescence)
    matRefs.current.forEach((mat, i) => {
        if (mat.iridescence !== undefined) {
             // Subtle oscillation of iridescence
             mat.iridescence = 0.5 + Math.sin(time * 0.5 + i) * 0.2;
        }
        if (mat.transmission && mat.transmission > 0) {
             // Subtle pulse of jelly materials
             mat.transmission = 0.85 + Math.sin(time * 2) * 0.1;
        }
    });

    const throttleTime = qualityLevelRef.current === 0 ? 100 : (isMobile ? 60 : 40);
    let currentFrameGesture: 'TREE' | 'FLOAT' | 'FOCUS' | null = null;
    
    if (now - lastGestureTimeRef.current > throttleTime) {
        lastGestureTimeRef.current = now;
        if (handLandmarkerRef.current && videoRef.current && videoRef.current.currentTime > 0) {
          try {
            const results = handLandmarkerRef.current.detectForVideo(videoRef.current, now);
            if (results.landmarks && results.landmarks.length > 0) {
              lastDetectionTimeRef.current = now;
              const landmarks = results.landmarks[0];
              const wrist = landmarks[0];
              const thumbTip = landmarks[4];
              const indexTip = landmarks[8];
              
              targetHandPosRef.current = { x: (wrist.x - 0.5) * 2, y: (wrist.y - 0.5) * 2 };
              
              const pinchDist = Math.hypot(thumbTip.x - indexTip.x, thumbTip.y - indexTip.y);
              if (pinchDist < 0.05) currentFrameGesture = 'FOCUS';
              else if (landmarks[8].y < landmarks[5].y && landmarks[12].y < landmarks[9].y && landmarks[16].y < landmarks[13].y) currentFrameGesture = 'FLOAT'; 
              else currentFrameGesture = 'TREE';
            }
          } catch (err) {}
        }
    }

    if (now - lastDetectionTimeRef.current > 2000 && stateRef.current !== 'TREE') {
        stateRef.current = 'TREE';
        setGesture('😴 自动休息');
        gestureHistoryRef.current = [];
    } else if (currentFrameGesture) {
        gestureHistoryRef.current.push(currentFrameGesture);
        if (gestureHistoryRef.current.length > 5) gestureHistoryRef.current.shift();
        const counts = { TREE: 0, FLOAT: 0, FOCUS: 0 };
        gestureHistoryRef.current.forEach(g => counts[g as keyof typeof counts]++);
        
        let detectedState: 'TREE' | 'FLOAT' | 'FOCUS' | null = null;
        if (counts.FOCUS >= 3) detectedState = 'FOCUS';
        else if (counts.TREE >= 3) detectedState = 'TREE';
        else if (counts.FLOAT >= 3) detectedState = 'FLOAT';

        if (detectedState && detectedState !== stateRef.current) {
            if (detectedState === 'FOCUS') {
                stateRef.current = 'FOCUS';
                focusedPhotoIndex.current = (focusedPhotoIndex.current + 1) % photoMeshesRef.current.length;
                panRef.current = { x: 0, y: 0 };
                zoomRef.current = 1.0;
            } else {
                if (detectedState === 'FLOAT') {
                    cameraOffsetRef.current = { x: 0, y: 0 };
                    zoomRef.current = 1.0;
                }
                stateRef.current = detectedState;
            }
            setGesture(detectedState === 'TREE' ? '✊ 收集美好' : detectedState === 'FLOAT' ? '🖐 释放浪漫' : '🤏 珍藏回忆');
        }
    }

    visualHandPosRef.current.x += (targetHandPosRef.current.x - visualHandPosRef.current.x) * 0.15;
    visualHandPosRef.current.y += (targetHandPosRef.current.y - visualHandPosRef.current.y) * 0.15;
    if (cursorRef.current) {
        const cx = (visualHandPosRef.current.x + 1) / 2 * window.innerWidth;
        const cy = (visualHandPosRef.current.y + 1) / 2 * window.innerHeight;
        cursorRef.current.style.transform = `translate(${window.innerWidth - cx}px, ${cy}px)`;
        cursorRef.current.style.opacity = (now - lastDetectionTimeRef.current < 500) ? '1' : '0';
    }

    if (mainLightRef.current) mainLightRef.current.intensity = 1.5 + Math.sin(time * 1.5) * 0.4;
    
    if (starRef.current) {
        starRef.current.children[0].rotation.y = time * 0.5;
        starRef.current.position.lerp(new THREE.Vector3(0, stateRef.current === 'TREE' ? TREE_HEIGHT/2 + 2 : 8, 0), 0.05);
    }
    
    // Dynamic Fog Logic - optimized blur background
    if (sceneRef.current && sceneRef.current.fog) {
        const fog = sceneRef.current.fog as THREE.FogExp2;
        const targetDensity = stateRef.current === 'FOCUS' ? 0.04 : 0.012;
        fog.density += (targetDensity - fog.density) * 0.05;
    }

    if (stardustRef.current) {
        const positions = stardustRef.current.geometry.attributes.position.array as Float32Array;
        const randoms = stardustRef.current.geometry.attributes.aRandom.array as Float32Array;
        const count = positions.length / 3;
        stardustRef.current.rotation.y = time * 0.02;
        for(let i=0; i < count; i++) {
             const wave = Math.sin(time * 0.5 + positions[i*3] * 0.1 + randoms[i] * 10) * 0.02;
             positions[i*3+1] += wave;
        }
        stardustRef.current.geometry.attributes.position.needsUpdate = true;
    }

    if (snowRef.current) {
        const positions = snowRef.current.geometry.attributes.position.array as Float32Array;
        const step = qualityLevelRef.current < 2 ? 2 : 1; 
        for (let i = 0; i < positions.length / 3; i += step) {
            positions[i * 3 + 1] -= 0.1; 
            positions[i * 3] += Math.sin(time + i) * 0.02;
            if (positions[i * 3 + 1] < -30) positions[i * 3 + 1] = 30;
        }
        snowRef.current.geometry.attributes.position.needsUpdate = true;
    }

    const dummy = new THREE.Object3D();
    // Repulsion Logic (Physics Simulation)
    const repulsionRadius = 6.0;
    const repulsionStrength = 0.5;
    const handPos = handWorldPosRef.current;
    const isHandActive = now - lastDetectionTimeRef.current < 500 || isDraggingRef.current;

    particlesDataRef.current.forEach((p) => {
        let target = new THREE.Vector3();
        if (stateRef.current === 'TREE') {
            target.copy(p.treePos);
            p.currentScale = 1.0 + Math.sin(time * 5 + p.phase) * 0.1;
        } else {
            const angle = p.orbitStartAngle + time * p.orbitSpeed * 0.5;
            const r = p.orbitRadius + Math.sin(time + p.phase) * 2;
            target.set(Math.cos(angle) * r, p.orbitY + Math.sin(time * 0.8 + p.phase) * 3, Math.sin(angle) * r);
            p.currentScale = 0.8 + Math.sin(time * 2 + p.phase) * 0.2;
        }
        
        // --- Particle Interaction / Collision ---
        if (isHandActive && qualityLevelRef.current > 1) {
             const dist = p.currentPos.distanceTo(handPos);
             if (dist < repulsionRadius) {
                 const dir = p.currentPos.clone().sub(handPos).normalize();
                 const force = (repulsionRadius - dist) * repulsionStrength;
                 p.velocity.add(dir.multiplyScalar(force));
             }
        }
        // Damping velocity
        p.velocity.multiplyScalar(0.9);
        // Apply velocity to position temporarily for interaction effect
        const interactionPos = p.currentPos.clone().add(p.velocity);

        // Smoothly lerp towards target position (spring effect)
        p.currentPos.lerp(target, 0.05).add(p.velocity);
        
        p.currentRot.x += p.rotationSpeed.x;
        p.currentRot.y += p.rotationSpeed.y;
        
        dummy.position.copy(p.currentPos);
        dummy.rotation.set(p.currentRot.x, p.currentRot.y, p.currentRot.z);
        dummy.scale.setScalar(p.currentScale);
        dummy.updateMatrix();
        
        if (instancedMeshesRef.current[p.meshIndex]) {
            instancedMeshesRef.current[p.meshIndex].setMatrixAt(p.instanceId, dummy.matrix);
        }
    });
    instancedMeshesRef.current.forEach(mesh => mesh.instanceMatrix.needsUpdate = true);

    photoMeshesRef.current.forEach((group, i) => {
      const mesh = group as unknown as THREE.Group;
      const data = group.userData;
      let targetPos = new THREE.Vector3();
      let targetScale = 1;
      let lookAtPos: THREE.Vector3 | null = null;

      if (stateRef.current === 'TREE') {
        targetPos.copy(data.treePos);
        lookAtPos = targetPos.clone().multiplyScalar(2);
        targetScale = 0.8;
      } else if (stateRef.current === 'FOCUS' && i === focusedPhotoIndex.current) {
        targetPos.set(panRef.current.x, panRef.current.y, 25);
        targetScale = 3.5 * zoomRef.current;
      } else {
        const angle = data.orbitAngle + time * data.orbitSpeed * 0.3;
        targetPos.set(Math.cos(angle) * data.orbitRadius, data.orbitY + Math.sin(time + i) * 2, Math.sin(angle) * data.orbitRadius);
        lookAtPos = cameraRef.current.position;
      }
      mesh.position.lerp(targetPos, 0.05);
      const s = mesh.scale.x + (targetScale - mesh.scale.x) * 0.05;
      mesh.scale.setScalar(s);
      if (lookAtPos && stateRef.current !== 'FOCUS') mesh.lookAt(lookAtPos);
      else if (stateRef.current === 'FOCUS') mesh.rotation.set(0,0,0);
    });

    if (stateRef.current === 'FLOAT') {
      const hAngle = (visualHandPosRef.current.x + cameraOffsetRef.current.x) * Math.PI * 1.5;
      const vY = (visualHandPosRef.current.y + cameraOffsetRef.current.y) * 30;
      const r = 65 / Math.max(0.5, zoomRef.current);
      const target = new THREE.Vector3(Math.sin(hAngle) * r, -vY, Math.cos(hAngle) * r);
      cameraRef.current.position.lerp(target, 0.04);
      cameraRef.current.lookAt(0, 0, 0);
    } else if (stateRef.current === 'FOCUS') {
      cameraRef.current.position.lerp(new THREE.Vector3(0, 0, 45), 0.05);
      cameraRef.current.lookAt(0, 0, 0);
    } else {
      cameraRef.current.position.lerp(new THREE.Vector3(0, 0, 52), 0.04);
      cameraRef.current.lookAt(0, 6, 0);
    }

    composerRef.current?.render();
    frameIdRef.current = requestAnimationFrame(animate);
  }, [started]);

  useEffect(() => {
    if (started) frameIdRef.current = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(frameIdRef.current);
  }, [started, animate]);

  const handleStart = async () => {
    if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
      alert("请使用 HTTPS 或 localhost 访问。");
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ 
          video: { facingMode: "user", width: { ideal: 640 }, height: { ideal: 480 } } 
      });
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.onloadeddata = () => {
           videoRef.current?.play().catch(console.error);
           setStarted(true);
        };
      }
    } catch (err: any) {
      alert("摄像头启动失败: " + err.message);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const newPhotos: string[] = [];
      Array.from(e.target.files).forEach(file => newPhotos.push(URL.createObjectURL(file)));
      setUserPhotos(prev => [...prev, ...newPhotos]);
    }
  };
  
  const toggleMusic = () => {
      if (audioRef.current) {
          if (isPlaying) audioRef.current.pause();
          else audioRef.current.play();
          setIsPlaying(!isPlaying);
      }
  };

  return (
    <>
      <audio ref={audioRef} loop src="https://music.163.com/song/media/outer/url?id=2116535.mp3" />
      <div id="ui-layer">
        {!started ? (
            <div className="landing-overlay">
                <div className="landing-card">
                    <h1>Romantic Xmas</h1>
                    <p className="subtitle">✨ 唤醒指尖的浪漫魔法 ✨</p>
                    <div className="file-upload-container">
                        <label className="file-upload-label">
                            <input type="file" ref={fileInputRef} onChange={handleFileUpload} accept="image/*" multiple />
                            <span>📷 添加照片回忆 (可选)</span>
                        </label>
                        {userPhotos.length > 0 && <span className="photo-count">已选择 {userPhotos.length} 张</span>}
                    </div>
                    {loading ? <p style={{color:'#ffb7c5'}}>魔法资源加载中...</p> : (
                        <button className="btn" onClick={handleStart}>💫 开启体验</button>
                    )}
                </div>
            </div>
        ) : (
            <div className="hud-overlay">
                <div className="status-bar">
                    <div className="status-main">{gesture}</div>
                    <div className="status-hint">拳头:收集 • 五指:释放 • 捏合:珍藏</div>
                </div>
                <div className={`music-player ${isPlaying ? 'playing' : ''}`} onClick={toggleMusic}>
                    <div className="music-icon">🎵</div>
                </div>
            </div>
        )}
      </div>
      <div ref={cursorRef} id="hand-cursor">🍃</div>
      <video ref={videoRef} id="webcam-preview" className={started ? 'active' : ''} playsInline muted></video>
      <div ref={mountRef} id="canvas-container" style={{width: '100%', height: '100%'}} />
    </>
  );
};

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
